version: "3"
services:
  postgres:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      POSTGRES_DB: io_schedules
    volumes:
      - postgres-data:/var/lib/postgresql/data

  scheduleapp:
    build:
      context: .
      dockerfile: app.Dockerfile
    ports:
      - 8080
    restart: unless-stopped
    depends_on:
      - postgres

volumes:
  postgres-data:

